import type { OrienteeringMap } from "@/types/map";
import type { Event } from "@/types/event";
import type { RankingEntry } from "@/types/ranking";

export const sampleMaps: OrienteeringMap[] = [
  {
    id: "1",
    name: "昭和の森",
    prefecture: "千葉県",
    city: "千葉市",
    terrain_type: "forest",
    scale: "1:10000",
    contour_interval: 2.5,
    created_year: 2023,
    creator: "千葉OLクラブ",
    image_url: "/maps/showanomori.jpg",
    thumbnail_url: "/maps/showanomori_thumb.jpg",
    bounds: { north: 35.525, south: 35.51, east: 140.24, west: 140.22 },
    center: { lat: 35.5175, lng: 140.23 },
    tags: ["森林", "千葉", "インカレ"],
    description: "千葉市南部に位置する都市近郊の森林公園。起伏に富んだテレインで、インカレ会場としても使用。",
  },
  {
    id: "2",
    name: "渡良瀬遊水地",
    prefecture: "栃木県",
    city: "栃木市",
    terrain_type: "mixed",
    scale: "1:15000",
    contour_interval: 2.5,
    created_year: 2024,
    creator: "栃木県OL協会",
    image_url: "/maps/watarase.jpg",
    thumbnail_url: "/maps/watarase_thumb.jpg",
    bounds: { north: 36.26, south: 36.23, east: 139.72, west: 139.68 },
    center: { lat: 36.245, lng: 139.7 },
    tags: ["遊水地", "平坦", "全日本"],
    description: "広大な遊水地エリア。平坦地形で藪のナビゲーションが要求される独特のテレイン。",
  },
  {
    id: "3",
    name: "代々木公園",
    prefecture: "東京都",
    city: "渋谷区",
    terrain_type: "park",
    scale: "1:4000",
    contour_interval: 2,
    created_year: 2025,
    creator: "東京OLクラブ",
    image_url: "/maps/yoyogi.jpg",
    thumbnail_url: "/maps/yoyogi_thumb.jpg",
    bounds: { north: 35.674, south: 35.668, east: 139.698, west: 139.69 },
    center: { lat: 35.671, lng: 139.694 },
    tags: ["スプリント", "公園", "都市"],
    description: "都心のスプリント会場。複雑な歩道ネットワークと植生がナビゲーションの鍵。",
  },
  {
    id: "4",
    name: "菅平高原",
    prefecture: "長野県",
    city: "上田市",
    terrain_type: "forest",
    scale: "1:15000",
    contour_interval: 5,
    created_year: 2022,
    creator: "長野県OL協会",
    image_url: "/maps/sugadaira.jpg",
    thumbnail_url: "/maps/sugadaira_thumb.jpg",
    bounds: { north: 36.535, south: 36.51, east: 138.35, west: 138.32 },
    center: { lat: 36.5225, lng: 138.335 },
    tags: ["高原", "森林", "全日本"],
    description: "標高1300mの高原テレイン。針葉樹と広葉樹の混交林で走りやすく、ロングディスタンスに最適。",
  },
  {
    id: "5",
    name: "鳥取砂丘",
    prefecture: "鳥取県",
    city: "鳥取市",
    terrain_type: "sand",
    scale: "1:5000",
    contour_interval: 2.5,
    created_year: 2024,
    creator: "中四国OL協会",
    image_url: "/maps/tottori.jpg",
    thumbnail_url: "/maps/tottori_thumb.jpg",
    bounds: { north: 35.543, south: 35.537, east: 134.239, west: 134.23 },
    center: { lat: 35.54, lng: 134.235 },
    tags: ["砂丘", "特殊テレイン"],
    description: "日本最大の砂丘をフィールドにした唯一無二のテレイン。砂地での移動と高低差が特徴。",
  },
  {
    id: "6",
    name: "飯能アドベンチャーフォレスト",
    prefecture: "埼玉県",
    city: "飯能市",
    terrain_type: "forest",
    scale: "1:10000",
    contour_interval: 5,
    created_year: 2023,
    creator: "埼玉OLクラブ",
    image_url: "/maps/hanno.jpg",
    thumbnail_url: "/maps/hanno_thumb.jpg",
    bounds: { north: 35.875, south: 35.855, east: 139.34, west: 139.31 },
    center: { lat: 35.865, lng: 139.325 },
    tags: ["森林", "トレイル", "首都圏"],
    description: "首都圏からアクセス良好な丘陵森林。急斜面と尾根・谷のパターンが特徴的。",
  },
  {
    id: "7",
    name: "名城公園",
    prefecture: "愛知県",
    city: "名古屋市",
    terrain_type: "park",
    scale: "1:4000",
    contour_interval: 2,
    created_year: 2025,
    updated_year: 2025,
    creator: "愛知県OL協会",
    image_url: "/maps/meijo.jpg",
    thumbnail_url: "/maps/meijo_thumb.jpg",
    bounds: { north: 35.189, south: 35.183, east: 136.905, west: 136.897 },
    center: { lat: 35.186, lng: 136.901 },
    tags: ["スプリント", "公園", "城"],
    description: "名古屋城に隣接する都市公園。城壁や堀を含む複合的なスプリントテレイン。",
  },
  {
    id: "8",
    name: "吾妻山",
    prefecture: "福島県",
    city: "福島市",
    terrain_type: "forest",
    scale: "1:15000",
    contour_interval: 5,
    created_year: 2021,
    creator: "福島OLクラブ",
    image_url: "/maps/azuma.jpg",
    thumbnail_url: "/maps/azuma_thumb.jpg",
    bounds: { north: 37.77, south: 37.745, east: 140.27, west: 140.24 },
    center: { lat: 37.7575, lng: 140.255 },
    tags: ["山岳", "森林", "東北"],
    description: "東北を代表する山岳テレイン。変化に富んだ植生と急峻な地形が上級者を試す。",
  },
];

export const sampleEvents: Event[] = [
  {
    id: "1",
    name: "第50回全日本オリエンテーリング選手権大会",
    date: "2026-11-15",
    end_date: "2026-11-16",
    event_type: "official",
    location: { prefecture: "長野県", city: "上田市", venue: "菅平高原", lat: 36.5225, lng: 138.335 },
    organizer: "日本オリエンテーリング協会",
    map_id: "4",
    description: "ロングディスタンス・ミドルディスタンスの2日間。日本一を決める最高峰の大会。",
    classes: [
      { name: "M21E", distance_km: 12.5, climb_m: 450, controls: 22 },
      { name: "W21E", distance_km: 8.2, climb_m: 300, controls: 17 },
      { name: "M20", distance_km: 9.0, climb_m: 350, controls: 18 },
      { name: "W20", distance_km: 6.5, climb_m: 250, controls: 14 },
    ],
    status: "upcoming",
  },
  {
    id: "2",
    name: "関東スプリントシリーズ #3",
    date: "2026-03-15",
    event_type: "official",
    location: { prefecture: "東京都", city: "渋谷区", venue: "代々木公園", lat: 35.671, lng: 139.694 },
    organizer: "関東OL協会",
    map_id: "3",
    entry_url: "https://japan-o-entry.com/example",
    description: "都心で開催のスプリント大会。初心者から上級者まで楽しめるクラス設定。",
    classes: [
      { name: "ME", distance_km: 3.2, controls: 18 },
      { name: "WE", distance_km: 2.5, controls: 14 },
      { name: "M/WB", distance_km: 1.8, controls: 10 },
      { name: "M/WN", distance_km: 1.2, controls: 8 },
    ],
    status: "upcoming",
  },
  {
    id: "3",
    name: "千葉OL練習会",
    date: "2026-03-08",
    event_type: "training",
    location: { prefecture: "千葉県", city: "千葉市", venue: "昭和の森", lat: 35.5175, lng: 140.23 },
    organizer: "千葉OLクラブ",
    map_id: "1",
    description: "月例の練習会。フリーのスコアOイベント。誰でも参加可能。",
    classes: [
      { name: "スコアA", distance_km: 5.0, controls: 30 },
      { name: "スコアB", distance_km: 3.0, controls: 20 },
    ],
    status: "upcoming",
  },
  {
    id: "4",
    name: "第30回インカレロング",
    date: "2026-06-14",
    end_date: "2026-06-15",
    event_type: "official",
    location: { prefecture: "千葉県", city: "千葉市", venue: "昭和の森周辺", lat: 35.5175, lng: 140.23 },
    organizer: "日本学生OL連盟",
    map_id: "1",
    description: "大学オリエンテーリング最大の大会。ロング2日間。",
    classes: [
      { name: "ME", distance_km: 10.0, climb_m: 300, controls: 20 },
      { name: "WE", distance_km: 7.0, climb_m: 200, controls: 15 },
    ],
    status: "upcoming",
  },
  {
    id: "5",
    name: "中部スプリントカップ 2026",
    date: "2026-04-19",
    event_type: "official",
    location: { prefecture: "愛知県", city: "名古屋市", venue: "名城公園", lat: 35.186, lng: 136.901 },
    organizer: "中部OL協会",
    map_id: "7",
    description: "名古屋城エリアでのスプリント大会。複雑な地形を攻略せよ。",
    classes: [
      { name: "ME", distance_km: 3.5, controls: 20 },
      { name: "WE", distance_km: 2.8, controls: 16 },
      { name: "MJ/WJ", distance_km: 2.0, controls: 12 },
    ],
    status: "upcoming",
  },
  {
    id: "6",
    name: "全日本スプリント選手権 2025",
    date: "2025-10-05",
    event_type: "official",
    location: { prefecture: "東京都", city: "渋谷区", venue: "代々木公園", lat: 35.671, lng: 139.694 },
    organizer: "日本オリエンテーリング協会",
    map_id: "3",
    results_url: "#",
    description: "2025年のスプリント日本一決定戦。",
    classes: [
      { name: "M21E", distance_km: 3.8, controls: 22 },
      { name: "W21E", distance_km: 3.0, controls: 18 },
    ],
    status: "completed",
  },
];

export const sampleRankingsM21E: RankingEntry[] = [
  { rank: 1, athlete_name: "田中 太郎", club: "東大OLK", points: 1850, events_counted: 5, best_results: [{ event_name: "全日本選手権", date: "2025-11-15", rank: 1, points: 400 }, { event_name: "インカレロング", date: "2025-06-14", rank: 1, points: 380 }] },
  { rank: 2, athlete_name: "鈴木 一郎", club: "京大OLC", points: 1720, events_counted: 5, best_results: [{ event_name: "全日本選手権", date: "2025-11-15", rank: 2, points: 370 }, { event_name: "全日本スプリント", date: "2025-10-05", rank: 1, points: 380 }] },
  { rank: 3, athlete_name: "佐藤 健", club: "東北大OLC", points: 1650, events_counted: 5, best_results: [{ event_name: "全日本選手権", date: "2025-11-15", rank: 3, points: 350 }, { event_name: "インカレロング", date: "2025-06-14", rank: 2, points: 350 }] },
  { rank: 4, athlete_name: "高橋 翔", club: "早大OC", points: 1580, events_counted: 5, best_results: [{ event_name: "全日本選手権", date: "2025-11-15", rank: 5, points: 320 }, { event_name: "関東選手権", date: "2025-09-20", rank: 1, points: 340 }] },
  { rank: 5, athlete_name: "山田 隼人", club: "筑波大OB会", points: 1520, events_counted: 5, best_results: [{ event_name: "全日本選手権", date: "2025-11-15", rank: 4, points: 330 }, { event_name: "全日本スプリント", date: "2025-10-05", rank: 3, points: 330 }] },
  { rank: 6, athlete_name: "伊藤 大輝", club: "名大OLC", points: 1480, events_counted: 4, best_results: [{ event_name: "インカレロング", date: "2025-06-14", rank: 3, points: 340 }, { event_name: "中部選手権", date: "2025-09-27", rank: 1, points: 350 }] },
  { rank: 7, athlete_name: "渡辺 蓮", club: "慶應OB会", points: 1430, events_counted: 5, best_results: [{ event_name: "全日本選手権", date: "2025-11-15", rank: 6, points: 310 }, { event_name: "関東選手権", date: "2025-09-20", rank: 2, points: 320 }] },
  { rank: 8, athlete_name: "中村 優斗", club: "北大OLC", points: 1390, events_counted: 5, best_results: [{ event_name: "全日本選手権", date: "2025-11-15", rank: 7, points: 300 }, { event_name: "北海道選手権", date: "2025-08-30", rank: 1, points: 340 }] },
  { rank: 9, athlete_name: "小林 颯太", club: "東工大OLC", points: 1350, events_counted: 5, best_results: [{ event_name: "全日本スプリント", date: "2025-10-05", rank: 2, points: 360 }, { event_name: "インカレスプリント", date: "2025-05-17", rank: 1, points: 350 }] },
  { rank: 10, athlete_name: "加藤 拓海", club: "千葉OLクラブ", points: 1310, events_counted: 5, best_results: [{ event_name: "全日本選手権", date: "2025-11-15", rank: 8, points: 290 }, { event_name: "関東選手権", date: "2025-09-20", rank: 3, points: 310 }] },
];

export const sampleRankingsW21E: RankingEntry[] = [
  { rank: 1, athlete_name: "山本 花", club: "東大OLK", points: 1780, events_counted: 5, best_results: [{ event_name: "全日本選手権", date: "2025-11-15", rank: 1, points: 400 }] },
  { rank: 2, athlete_name: "松本 さくら", club: "京大OLC", points: 1680, events_counted: 5, best_results: [{ event_name: "全日本選手権", date: "2025-11-15", rank: 2, points: 370 }] },
  { rank: 3, athlete_name: "井上 美咲", club: "筑波大OLC", points: 1600, events_counted: 5, best_results: [{ event_name: "全日本選手権", date: "2025-11-15", rank: 3, points: 350 }] },
  { rank: 4, athlete_name: "木村 凛", club: "早大OC", points: 1540, events_counted: 5, best_results: [{ event_name: "インカレロング", date: "2025-06-14", rank: 1, points: 380 }] },
  { rank: 5, athlete_name: "林 結衣", club: "慶應OB会", points: 1490, events_counted: 4, best_results: [{ event_name: "全日本スプリント", date: "2025-10-05", rank: 1, points: 380 }] },
  { rank: 6, athlete_name: "清水 陽菜", club: "名大OLC", points: 1440, events_counted: 5, best_results: [{ event_name: "全日本選手権", date: "2025-11-15", rank: 4, points: 330 }] },
  { rank: 7, athlete_name: "吉田 楓", club: "東北大OLC", points: 1400, events_counted: 5, best_results: [{ event_name: "全日本選手権", date: "2025-11-15", rank: 5, points: 320 }] },
  { rank: 8, athlete_name: "藤田 真央", club: "北大OLC", points: 1360, events_counted: 5, best_results: [{ event_name: "北海道選手権", date: "2025-08-30", rank: 1, points: 340 }] },
];
